version: "3.7"
services:
  db:
    container_name: sql_server
    build: /home/guilherme/docker-livy/SQLServer
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Mudar@123
      MSSQL_DB: analytics
      MSSQL_USER: Admin
      MSSQL_PASSWORD: Mudar@123
    ports:
        - "1433:1433"
  web:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      FLASK_DEBUG: "on"
      FLASK_APP: ./app.py
    restart: always
    ports:
     - "5001:5001"
    depends_on:
      - redis
    volumes: ['./api:/api']
  worker:
    build:
      context: ./celery-queue
      dockerfile: Dockerfile.dev
    command: celery -A tasks worker -l info -E
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
    volumes: ['./celery-queue:/queue']
  monitor:
    build:
      context: ./celery-queue
      dockerfile: Dockerfile.dev
    ports:
     - "5555:5555"
    command:  ['celery', 'flower', '-A', 'tasks']
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
      - worker
    volumes: ['./celery-queue:/queue']

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  db:
networks:
  net:
    driver: bridge